### before running, please make sure to add the dataset to the dataset list
# "chartverse_sft_600k": {
#   "file_name": YOUR_DATASET_FILE_PATH,
#   "columns": {
#     "prompt": "question",
#     "response": "answer",
#     "images": "images",
#   }
# },


### model
model_name_or_path: Qwen3/Qwen3-VL-8B-Instruct
image_max_pixels: 3211264
image_min_pixels: 802816
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
flash_attn: fa2
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
deepspeed: ds_z3_config.json

### dataset
dataset: chartverse_sft_600k
template: qwen3_vl
cutoff_len: 22000
enable_thinking: true
packing: true
max_samples: 100000000
overwrite_cache: false
preprocessing_num_workers: 32
dataloader_num_workers: 4

### output
output_dir: saves/chartverse_sft_8b
logging_steps: 1
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null